blog/urls.py
from django.urls import path
from . import views

app_name="posts"
urlpatterns = [
    path("posts/", views.posts_list, name="list"),
    path("posts/<int:id>", views.post_detail, name="detail"),
]

books/urls.py
from django.urls import path
from . import views

app_name="books"
urlpatterns = [
    path("", views.books_list, name="list"),
    path("<int:id>/", views.book_details, name="details"),
]

firstblood/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mathematics.urls")),
    path("blog/", include("blog.urls")),
    path("books/", include("books.urls")),

]

mathematics/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.hello),
    path("hello/", views.hello),
    path("hello/<name>/", views.hello),
    path("mathematics/<operation>/<int:a>/<int:b>", views.calculator)  # to wymaga utworzenia funkcji calculator
]

blog/models.py
from django.db import models

# Create your models here.

books/models.py
from django.db import models

# Create your models here.

blog/views.py
from django.shortcuts import render

from .services import FakePostService


def posts_list(request):
    posts = FakePostService.list()

    return render(
        request=request, 
        template_name="blog/list.html",
        context={"posts":posts}
    )

def post_detail(request, id):
    pass

books/views.py
from django.shortcuts import render
from dataclasses import dataclass
# Create your views here.

@dataclass
class Book:
    id: int
    title: str
    description: str

def books_list(request):
    books = [
        Book(1, "Pan Tadeusz", "Ala ma kota"), 
        Book(2, "Krzyzacy", "Lubie biegac")
    ]

    return render(
        request=request, 
        template_name="books/list.html",
        context={"books":books}
    )

def book_details(request, id):
    pass

mathematics/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpRequest
from mathematics.services import AlgebraService
# Create your views here.

from django.template.loader import render_to_string


# def hello(request, name="World!"):
#     rendered = render_to_string("mathematics/calculations.html", {"text": f"Hello {name}"})
#     return HttpResponse(rendered)

# def hello(request, name="World!"):
#     return render(
#         request, 
#         "mathematics/calculations.html",
#          {"text": f"Hello {name}"}
#     )


def hello(request, name="World!"):
    return render(
        request=request, 
        template_name="mathematics/calculations.html",
        context={
            "text": f"Hello {name}",
            "text2": "Ala ma kota",  
            "lista": [10, 2, "a", "b"],
            "tupla": ("x", "y", 100),
            "zbior": {1, 2, 3},
            "slownik": {"klucz": "wartosc"}
        }
    )


def calculator(request: HttpRequest , operation: str, a: int, b: int) -> HttpResponse:
    
    try:
        result = AlgebraService.calculate(operation, a, b)
    except ValueError as e:
        return HttpResponse(f"{e}")
    except KeyError:
        return HttpResponse("Niepoprawna operacja")
    return HttpResponse(f"{result}")

blog/templates/blog/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista postow</title>
</head>
<body>
    <h1>Posty:</h1>
    <ul>
        {% for post in posts %}
            <li><a href="{% url 'posts:detail' post.id %}">{{ post.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

books/templates/books/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista postow</title>
</head>
<body>
    <h1>Ksiazki:</h1>
    <ul>
        {% for book in books %}
            <li><a href="{% url 'books:details' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

mathematics/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

mathematics/templates/mathematics/calculations.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Hello Django</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
<h1>Django First Blood Application</h1>
<div>
    <ul>
        <li><a href="/hello" >Hello world endpoint</a></li>
        <li><a href="/hello/ALX" >Hello ALX endpoint</a></li>
        <li><a href="/hello/Rafal" >Hello Rafal endpoint</a></li>
    </ul>
</div>

{{ text }}

<p>{{ text50 }}</p>

{% if lista.0 == 10 %}
<p>{{ lista }}</p>
{% endif %}
<p>{{ lista.3 }}</p>






<p>{{ tupla }}</p>

<p>{{ zbior }}</p>
<ol>
{% for el in zbior %}
    <li>{{ el }}</li>
{% endfor %}
</ol>

<p>{{ slownik }}</p>
<p>{{ slownik.klucz }}</p>



<div>
    <ul>
        <li><a href="/blog/posts/1" >Post pierwszy</a></li>
        <li><a href="/blog/posts/2"  >Hello ALX endpoint</a></li>
        <li><a href="/blog/posts/3"  >Hello Rafal endpoint</a></li>
        ...
    </ul>
</div>

</body>
</html>